### PR TITLE
Cosmetic fixe - Delete a whitespace before a colon

### PR DESCRIPTION
**Pull request by Galixte**
Update for cookiepolicy_manage.html file.

### CODE REVIEW

**Comment by david63** [comment]
That is by design

**Comment by Galixte** [comment]
Hi,

what design ? why two whitespaces instead of one ?

In french languages or english you see often two whitespaces in sentence ? Not me.

**Comment by Galixte** [comment]
Hi @david63,

please.

**Comment by Galixte** [comment]
Thanks.

**Pull request merged**
